import jsPDF from "jspdf"
import type { CVReview } from "@/types/cv-review"

export function generatePDF(review: CVReview, fileName: string, jobRole: string) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.width
  const margin = 20
  const lineHeight = 7
  let yPosition = margin

  // Helper function to add text with word wrapping
  const addText = (text: string, fontSize = 12, isBold = false) => {
    doc.setFontSize(fontSize)
    doc.setFont("helvetica", isBold ? "bold" : "normal")

    const lines = doc.splitTextToSize(text, pageWidth - 2 * margin)

    // Check if we need a new page
    if (yPosition + lines.length * lineHeight > doc.internal.pageSize.height - margin) {
      doc.addPage()
      yPosition = margin
    }

    doc.text(lines, margin, yPosition)
    yPosition += lines.length * lineHeight + 5
  }

  // Header
  addText("CV Review Report", 20, true)
  addText(`File: ${fileName}`, 12)
  if (jobRole) {
    addText(`Target Role: ${jobRole}`, 12)
  }
  addText(`Generated: ${new Date().toLocaleDateString()}`, 10)
  addText(`Reviewed by: ${review.provider} AI`, 10)

  yPosition += 10

  // Overall Score
  addText("OVERALL SCORE", 16, true)
  addText(`${review.score}/100`, 14, true)
  yPosition += 5

  // Strengths
  addText("STRENGTHS", 14, true)
  review.strengths.forEach((strength, index) => {
    addText(`${index + 1}. ${strength}`, 11)
  })
  yPosition += 5

  // Areas for Improvement
  addText("AREAS FOR IMPROVEMENT", 14, true)
  review.weaknesses.forEach((weakness, index) => {
    addText(`${index + 1}. ${weakness}`, 11)
  })
  yPosition += 5

  // Structure Feedback
  addText("STRUCTURE & FORMAT FEEDBACK", 14, true)
  addText(review.structureFeedback, 11)
  yPosition += 5

  // Grammar Feedback
  addText("GRAMMAR & CLARITY FEEDBACK", 14, true)
  addText(review.grammarFeedback, 11)
  yPosition += 5

  // ATS Compatibility
  addText("ATS COMPATIBILITY", 14, true)
  addText(`Score: ${review.atsScore}/100`, 12, true)
  addText(review.atsFeedback, 11)
  yPosition += 5

  // Suggestions
  addText("IMPROVEMENT SUGGESTIONS", 14, true)
  review.suggestions.forEach((suggestion, index) => {
    addText(`${index + 1}. ${suggestion}`, 11)
  })

  // Footer
  yPosition = doc.internal.pageSize.height - margin
  doc.setFontSize(8)
  doc.setFont("helvetica", "normal")
  doc.text("Generated by CV Roaster - Your AI-Powered Career Assistant", margin, yPosition)

  // Save the PDF
  doc.save(`CV-Review-${fileName.replace(/\.[^/.]+$/, "")}-${Date.now()}.pdf`)
}
